{% set version = "2.21" %}
{% set name = "palp" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://hep.itp.tuwien.ac.at/~kreuzer/CY/palp/{{ name }}-{{ version }}.tar.gz
  sha256: 7e4a7bf219998a844c0bcce0a176e49d0743cb4b505a0e195329bf2ec196ddd7

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:

test:
  commands:
    - poly.x -h

about:
  home: http://hep.itp.tuwien.ac.at/~kreuzer/CY/CYpalp.html
  license: GPL-2.0-later
  license_file: COPYING
  summary: PALP - a Package for Analyzing Lattice Polytopes

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
