appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: fFA/Or/oKU5CRIckoebbHWdCnI0Vn2IytDWuWTekEpDiCW+a2A6MnFLyAmhR991C04dB8zVXfQUnDHoHEQjVKLFhQoyBnIpkdk9Iw68zT6ihN2RC7qHLxSqdIRMmIHsH4id6+tnyw9btp8B174zLQ+cDepyxX/Q4N2k0MzaxmL9AY3I+aeuZT7RVjJyvcZzgGww3viaG6A6mOXXYIEyWWXyPPRGCblxa+cCgIeeE1+xcdSC10gM81jCWzel8ZGlcl6L7TNWy5AfzTtMMCKS1hEwiCt54rR4e3a0VUTlG95Fcz0MdkRjCQW8jStT1GQC6eXS4YcucEGoLNsIpdqwGiOaL95U0V1wdWQyt82eh7THmc/IaAKtX9UWThi3URl3ngxQPGPN9r/SfcYWZj0Qgz1nhdLRPCCvOwApuV8Y4M6jVim+D6W7O+SthekBUJXpqj+brcsiSHZiSAzauzlfgNPE0aOY6sQR6QSNLn2TcLEbllxxEjiRGuy7IgjLbNyvZYG+AedJLYDrvdig3geHGl9s9npa0kbyc8i4QuoJhuAavacOOUq/xRUqwYdiAhMS75ReTGL+Z5KkiKtMa34haLKRTYcCRVjMvQ3LZSpMXjQuM9fhs816HET9OOt9kklmSanOmuEToL1eARClX4qbSFHAzN57N7ri6XMTo8UuXfQs=}
