travis:
  secure:
    BINSTAR_TOKEN: mZcFciiKzBRQgBeHEJCzDh4AzxbWW+Vmc4ZuW5TL88VBakpRot58xB2g0jp9GUOWncTsO0Pr7H6VyvpFrlT6V3Df48bal+zjShTw51/moPefA0Tn2+A/1ZPR6HQbAbSr6k3zCfwyYY31HS/tzk86wYBoixlE+qmFlqVwJrEJrzvrk5BqjDa3bxYxbWh0JErnsAtRqyyXFpjxUsHoLgvO/1/Sf2G6C9Q4OwrFFFbyaSS/MfiwHuF507/5H/Q9vVSb7J9lpe0C0U/0NimZLFh/7NVUqrfcy4qUvYhdKI+bm4nT2jee+bcKSJodNd45PYATlAwu87XwhqqSndjEPGWDVgvFWCYr3WkqMEopU9BLoiGuVVEjKy3nlbZK31TBtxgQ7C1Zr8tK/lgldU+oWTcxgUHVdzCFNFcuqvSOofrerPl8J3aLhNT6230JGA1q5dk8FTq09Ivq4/tTwq1O1dpqa5TatfZED7MYrvu1yhb8J++0p1/XCPAFmHNZrfSeWf4vBZFz+dSvJZWLVs5R+E48W//FZxThUAlX4YofXz4ICtlSyfJ9CJjPeJhWrB82KmiitBXN9Dkbe0YeYdutW9jxoYrQEtmOfLs5YscCazK8DWFcfIrOIoF7zniqJjOgDyEN0IzqLwK3H3x0C3irdS74TgiRNysazSZS66Ic04DqQwU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
